<p>1. Importa la librería de NumPy. </p>

In [2]:
import numpy as np 

<p>2. Crea un array de 1 dimension y 10 elementos.</p>

In [7]:
array =  np.random.randint(10, size = 10)
array 

array([6, 3, 3, 9, 3, 3, 4, 1, 0, 5])

<p>3. Reemplaza todos los números impares por el valor "impar" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.</p>

In [8]:
arrayn = []

for i in array:
    if i%2 == 0:
        arrayn.append("par")
    else:
        arrayn.append("impar")

In [11]:
arrayn

10

<p>4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.</p>

In [12]:
arrayan = np.reshape(arrayn, (2,5))
arrayan

array([['par', 'impar', 'impar', 'impar', 'impar'],
       ['impar', 'par', 'impar', 'par', 'impar']], dtype='<U5')

<p>5. Extrae los elementos comunes de los siguientes arrays</p>
<ul>
<li>array1 = np.array([1,2,3,2,3,4,3,4,5,6])</li>
<li>array2 = np.array([7,2,10,2,7,4,9,4,9,8])</li>
</ul>

In [13]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [14]:
np.intersect1d(array1,array2)

array([2, 4])

<p>6. Extraed los elementos que están en el array1 pero no en el array2.</p>

In [16]:
np.setdiff1d(array1,array2)

array([1, 3, 5, 6])

<p>7.Extraed las posiciones donde tengamos elementos que sean iguales.</p>

In [18]:
array_iguales, array1index, array2index = np.intersect1d(array1, array2, return_indices=True)

In [19]:
print(array1index,array2index)

[1 5] [1 5]


<p>8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.</p>

In [22]:
array3 = np.random.randint(50, size = (3,5))
array3

array([[45,  2, 37, 27, 27],
       [25,  6, 35, 42,  3],
       [21, 17,  9, 44,  4]])

In [27]:
array3_lista = []
for i in array3:
    for j in i:
        if  j < 10 or j > 40:
            array3_lista.append(j)
        

In [28]:
array3_lista

[45, 2, 6, 42, 3, 9, 44, 4]

<p>9.Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.</p>

In [29]:
array4 = np.random.uniform(5,10, size = (5,3))

In [30]:
array4

array([[5.35427937, 6.0208882 , 6.03011767],
       [7.34351905, 8.89791728, 7.86137042],
       [6.20255966, 9.61441206, 5.97962057],
       [9.91143948, 6.56506637, 9.97640872],
       [6.8878053 , 8.19211995, 9.3488584 ]])

<p>10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20</p>

In [31]:
array5 = np.random.randint(1,20, size = (2,4,7))
array5

array([[[16, 13, 10, 14, 18, 12,  5],
        [ 3,  1, 14, 14, 16, 12, 11],
        [ 4,  8,  2, 12,  1, 15, 16],
        [ 6,  3, 19, 13,  5,  7,  8]],

       [[ 4,  5, 12, 15, 18, 16, 14],
        [ 5,  4,  6, 18, 19,  2, 10],
        [ 8, 16,  9,  6,  7,  8, 10],
        [ 4, 11,  5,  6,  4, 10,  1]]])

<li>Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas</li>

In [32]:
array6 = np.transpose(array5, (1,2,0))

In [35]:
array6

array([[[16,  4],
        [13,  5],
        [10, 12],
        [14, 15],
        [18, 18],
        [12, 16],
        [ 5, 14]],

       [[ 3,  5],
        [ 1,  4],
        [14,  6],
        [14, 18],
        [16, 19],
        [12,  2],
        [11, 10]],

       [[ 4,  8],
        [ 8, 16],
        [ 2,  9],
        [12,  6],
        [ 1,  7],
        [15,  8],
        [16, 10]],

       [[ 6,  4],
        [ 3, 11],
        [19,  5],
        [13,  6],
        [ 5,  4],
        [ 7, 10],
        [ 8,  1]]])