<p>1. Importa la librería de NumPy. </p>

In [2]:
import numpy as np 

<p>2. Crea un array de 1 dimension y 10 elementos.</p>

In [3]:
array =  np.random.randint(10, size = 10)
array 

array([8, 3, 3, 9, 9, 2, 1, 2, 9, 6])

<p>3. Reemplaza todos los números impares por el valor "impar" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.</p>

In [4]:
arrayn = []

for i in array:
    if i%2 == 0:
        arrayn.append("par")
    else:
        arrayn.append("impar")

In [5]:
arrayn

['par',
 'impar',
 'impar',
 'impar',
 'impar',
 'par',
 'impar',
 'par',
 'impar',
 'par']

<p>4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.</p>

In [6]:
arrayan = np.reshape(arrayn, (2,5))
arrayan

array([['par', 'impar', 'impar', 'impar', 'impar'],
       ['par', 'impar', 'par', 'impar', 'par']], dtype='<U5')

<p>5. Extrae los elementos comunes de los siguientes arrays</p>
<ul>
<li>array1 = np.array([1,2,3,2,3,4,3,4,5,6])</li>
<li>array2 = np.array([7,2,10,2,7,4,9,4,9,8])</li>
</ul>

In [7]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [8]:
np.intersect1d(array1,array2)

array([2, 4])

<p>6. Extraed los elementos que están en el array1 pero no en el array2.</p>

In [9]:
np.setdiff1d(array1,array2)

array([1, 3, 5, 6])

<p>7.Extraed las posiciones donde tengamos elementos que sean iguales.</p>

In [10]:
array_iguales, array1index, array2index = np.intersect1d(array1, array2, return_indices=True)

In [11]:
print(array1index,array2index)

[1 5] [1 5]


<p>8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.</p>

In [12]:
array3 = np.random.randint(50, size = (3,5))
array3

array([[32, 24,  2, 47,  3],
       [ 7,  4,  0, 41, 16],
       [39,  8,  4, 22, 42]])

In [13]:
array3_lista = []
for i in array3:
    for j in i:
        if  j < 10 or j > 40:
            array3_lista.append(j)
        

In [14]:
array3_lista

[2, 47, 3, 7, 4, 0, 41, 8, 4, 42]

<p>9.Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.</p>

In [15]:
array4 = np.random.uniform(5,10, size = (5,3))

In [16]:
array4

array([[7.50987587, 8.52700595, 9.39857418],
       [9.58192798, 5.93618538, 5.90364238],
       [7.19488064, 5.07502625, 5.16027305],
       [6.33758773, 8.57055912, 5.85906388],
       [8.65614226, 5.43183666, 8.31236262]])

<p>10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20</p>

In [17]:
array5 = np.random.randint(1,20, size = (2,4,7))
array5

array([[[ 4,  1,  8,  2,  5,  6, 17],
        [ 2,  1, 17, 15,  5,  7,  8],
        [12,  1, 16,  2,  5, 18, 16],
        [11, 15, 19,  7, 11, 10, 17]],

       [[16, 17,  9,  6, 12, 16,  3],
        [ 1, 13, 15,  3, 14,  7,  3],
        [ 2,  9, 17,  5,  5,  1, 12],
        [ 7, 19, 10, 11, 18,  3,  1]]])

<li>Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas</li>

In [18]:
array6 = np.transpose(array5, (1,2,0))

In [19]:
array6

array([[[ 4, 16],
        [ 1, 17],
        [ 8,  9],
        [ 2,  6],
        [ 5, 12],
        [ 6, 16],
        [17,  3]],

       [[ 2,  1],
        [ 1, 13],
        [17, 15],
        [15,  3],
        [ 5, 14],
        [ 7,  7],
        [ 8,  3]],

       [[12,  2],
        [ 1,  9],
        [16, 17],
        [ 2,  5],
        [ 5,  5],
        [18,  1],
        [16, 12]],

       [[11,  7],
        [15, 19],
        [19, 10],
        [ 7, 11],
        [11, 18],
        [10,  3],
        [17,  1]]])